apiVersion: v1
kind: Pod
metadata:
  name: fortio-loadgen
  labels:
    app: fortio-loadgen
spec:
  restartPolicy: Never
  containers:
    - name: fortio
      image: fortio/fortio:latest
      command: ["fortio", "server", "-http-port", "disabled", "-grpc-port", "disabled"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
